export const DataProjects = [
  {
    title: 'All-Digital-Asset',
    url: 'https://maksimka241e.github.io/All-Digital-Asset-/build/',
    img: 'https://i.postimg.cc/DzgJc10h/img1.png',
    text: 'Адаптивный сайт цифровых активов "All-Digital-Asset"',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'Alukas',
    url: 'https://maksimka241e.github.io/Alukas/build/index.html',
    img: 'https://i.postimg.cc/9XS41mmD/2024-09-16-23-17-22.png',
    text: 'Адаптивный сайт ювелирных украшений "Alukas"',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'Ink. House',
    url: 'https://maksimka241e.github.io/House/build/index.html',
    img: 'https://i.postimg.cc/yY4Rs1ww/2024-09-16-23-18-39.png',
    text: 'Адаптивный сайт картин с корзиной "Ink. House"',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'POSH',
    url: 'https://maksimka241e.github.io/auto-parts/build/',
    img: 'https://i.postimg.cc/63hQKKnN/2024-09-16-23-27-09.png',
    text: 'Адаптивный сайт запчастей "POSH"',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'SUPPORT GROUP',
    url: 'https://maksimka241e.github.io/servis-it/build/index.html',
    img: 'https://i.postimg.cc/B6NJygfS/2024-09-16-23-28-10.png',
    text: 'Адаптивный сайт it "SUPPORT GROUP"',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'Backet',
    url: 'https://maksimka241e.github.io/basket/build/index.html',
    img: 'https://i.postimg.cc/8PxNqc96/2024-09-16-23-29-02.png',
    text: 'Адаптивный сайт техники с корзиной',
    skills: 'Стек: HTML, CSS, JS',
  },
  {
    title: 'Todo App',
    url: 'https://maksimka241e.github.io/todolistReact/',
    img: 'https://i.postimg.cc/2yVNtNxG/2024-09-16-23-30-16.png',
    text: 'Адаптивный сайт todo list',
    skills: 'Стек: HTML, CSS, React',
  },
  {
    title: 'ТЕЛЕБИТ',
    url: 'https://maksimka241e.github.io/newShops/',
    img: 'https://i.postimg.cc/W1Rc5Kqm/2024-09-16-23-31-25.png',
    text: 'Адаптивный сайт техники со всем функционалом "ТЕЛЕБИТ"',
    skills: 'Стек: HTML, CSS, React',
  },
  {
    title: 'Stories',
    url: 'https://maksimka241e.github.io/sorites/',
    img: 'https://i.postimg.cc/fLRG3Q1s/2024-09-16-23-32-10.png',
    text: 'Адаптивный магазин одежды со всем функционалом "Stories"',
    skills: 'Стек: HTML, CSS, React, Redux, ESLint, Prettier, Supabase',
  },
]
